### ISSUE TITLE
'Set Batch' instruction has incomplete parameter specification

### ISSUE THREAD

**Issue by qhenckel** [awilliamson/ic10-language-support#3]
The set batch (sb) instruction only lists registers as inputs for it's third parameter.
> sb (r?|num) type r?

But it should instead allow numbers as well: `sb (r?|num) type (r?|num)`

This causes valid commands like:
`sb 247344692 On 1`
to incorrectly be marked as errors since a number is not the correct type.
![image](https://github.com/awilliamson/ic10-language-support/assets/5070896/77cdaa04-a495-412b-a833-fd1f23068ea8)

Other similar instructions like the Set (s) correctly allow numbers for the third parameter:
> s d? type (r?|num)

**Comment by awilliamson** [comment]
Thanks @qhenckel this issue is actually related to the language server that the VSCode Extension is bundling. This is a problem with upstream, as mentioned from @Xandaros from https://github.com/Xandaros/ic10lsp

Talking with them now about updating and updating VSCode Extension. In future, we're looking at how to do this automatically to push new updates downstream.
